# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=200, unique=True)),
                ('planet_size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('planet_distance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('planet_ordinality', models.IntegerField(unique=True)),
            ],
        ),
    ]
