# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetmodel',
            name='planet_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
