# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_planetmodel_planet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetmodel',
            name='planet_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='planetmodel',
            name='planet_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
