# Generated by Django 2.0.4 on 2018-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='ordinality',
            field=models.IntegerField(help_text='Enter ordinality of planet'),
        ),
    ]
