# Generated by Django 2.0.1 on 2018-01-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='Description',
            field=models.TextField(default='Enter Description..'),
        ),
    ]
