# Generated by Django 2.0.1 on 2018-01-10 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('Ordinality', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.TextField()),
            ],
        ),
    ]
